// This file is automatically generated from CMake
#ifndef UTILS_PATHS_H
#define UTILS_PATHS_H

#define PROTO_ROOT_PATH "/home/eric/src/eih/"
#define PROTO_DATA_PATH "/home/eric/src/eih/data/"

#endif // ifndef UTILS_PATHS_H
